name = "novae-api"
main = "src/index.ts"
compatibility_date = "2026-07-01"
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

[env.production]
name = "novae-api"
workers_dev = true

[env.development]
name = "novae-api-dev"
workers_dev = true

[env.production.observability]
enabled = true
head_sampling_rate = 1

[env.development.observability]
enabled = true
head_sampling_rate = 1
